version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 50
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 50
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 8
  return-statements:
    config:
      threshold: 8
exclude_patterns:
  - "app/config/**"
